# |------------------------------------------------------------------------| #
# | #                                                                    # | #
# | #                     --------------------------                     # | #
# | #                     | BLP v2.0.0 by xDec0de_ |                     # | #
# | #                     --------------------------                     # | #
# | #                                                                    # | #
# |------------------------------------------------------------------------| #

Updater:
  Check: true
  Permission: "blp.updates"
Reload:
  Permission: "blp.reload"
